### ISSUE TITLE
TypeError: unhashable type: 'EDecimal'

### ISSUE THREAD

**Issue by izmcm** [Thijsvanede/AppScanner#1]
Hello :)

I got the following error when using Appscanner's `Preprocessor` class with some pcaps:
```
preprocessor = Preprocessor(verbose = True)
X, y = preprocessor.process(files = pcaps,
                            labels = labels)
```

```
{...}
     65             # Add length of packet to flow
---> 66             result[key] = result.get(key, []) + [length]
     67 
     68         # Convert lengths to numpy array.

TypeError: unhashable type: 'EDecimal'
```

Investigating the code I could see that EDecimal is a type from scapy lib. I corrected this error just by adding a float type casting to line 66 of `reader.py`

```
  data = [float(packet.time),
          int(ipaddress.ip_address(packet["IP"].src)),
          int(ipaddress.ip_address(packet["IP"].dst)),
          packet["TCP"].sport,
          packet["TCP"].dport,
          packet["IP"].len]
```

I'm using `Scapy Version 2.4.4`

**Comment by Thijsvanede** [comment]
Thank you very much for spotting the bug and adding the fix! I have merged it into the GitHub version

**Comment by baobao1997** [comment]
![image](https://github.com/Thijsvanede/AppScanner/assets/34308776/7f63fc18-4e82-44c9-bb7a-998e94beed4f)
line 96 of flow.py also needs to add a float-type casting.

**Comment by Thijsvanede** [comment]
The documentation of `key()` in `flow.py` specifies that timestamp should already be a float, and from a quick run of the code, it looks like that is already the case. Can you provide an example script/input where this goes wrong?

**Comment by baobao1997** [comment]
嘿，你好，已收到
