### ISSUE TITLE
Min-Max Scaler

### ISSUE THREAD

**Issue by ViktorAxelsen** [Thijsvanede/AppScanner#5]
Hello. Your project is nice and I'd like to use it for my reproducing work. But when I look at the source code, it seems that the feature extractor does not apply a min-max scaler to the output feature, which was introduced in the AppScanner original paper?

**Comment by Thijsvanede** [comment]
Indeed, we did not implement that in our repository to allow for closer inspection of the actual values.
However, using the [sklearn.preprocessing.MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html), it is quite straightforward to apply it over the given data:

```python
# Imports
from appscanner.preprocessor import Preprocessor
from appscanner.appscanner   import AppScanner
from sklearn.preprocessing   import MinMaxScaler

# Create preprocessor
preprocessor = Preprocessor()
# Load from files
X_train, y_train = preprocessor.process(
    files  = ['<path_file_1>', ..., '<path_file_n>'], # Path   to your own train pcap files
    labels = ['<label_1>'    , ..., '<label_n>'],     # Labels of your own train pcap files
)

# Load from files
X_test, y_test = preprocessor.process(
    files  = ['<path_file_1>', ..., '<path_file_n>'], # Path   to your own test pcap files
    labels = ['<label_1>'    , ..., '<label_n>'],     # Labels of your own test pcap files
)

# Scale features
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# Pass through appscanner
scanner = AppScanner(threshold=0.9)

# Fit scanner
scanner.fit(X_train, y_train)
# Predict labels of test data
y_pred = scanner.predict(X_test)
```

I have just added an `/example/example.py` script to the repository showing how to do this.
